CREATE PROC SPEMPLOYEESALARY
	@EMAPLOYEEID INT,
	@MONTH VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON;
	(SELECT EMPLOYEENAME,DESIGNATION,SALARY 
	FROM EMPLOYEES EMP INNER JOIN SALARY SAL 
	ON EMP.EMPLOYEEID=SAL.EMPLOYEEID 
	WHERE MONTH=@MONTH)
	FOR JASON PATH
END
