CREATE PROC SPEMPLOYEESALARY
	@EMAPLOYEEID INT,
	@MONTH VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON;
	(SELECT EMPLOYEENAME,DESIGNATION,SALARY 
	FROM EMPLOYEES EMP INNER JOIN SALARY SAL 
	ON EMP.EMPLOYEEID=SAL.EMPLOYEEID 
	WHERE MONTH=@MONTH)
	FOR JSON PATH
END
<<<<<<< HEAD

=======
GO
>>>>>>> 42e38ae18e2b2b0b69f090b1b3dd9ff05bd94067
