use AdventureWorks

CREATE TABLE SALES.MEDIAOUTLET (
MEDIAOUTLETID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
MEDIAOUTLETNAME NVARCHAR(40),
PRIMARYCONTACT NVARCHAR (50),
CITY NVARCHAR (50)
);

DROP TABLE SALES.MEDIAOUTLET;

CREATE TABLE SALES.PRINTMEDIAPLACEMENT( 
PRINTMEDIAPLACEMENTID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
MEDIAOUTLETID INT,
PLACEMENTDATE DATETIME,
PUBLICATIONDATE DATETIME,
RELATEDPRODUCTID INT,
PLACEMENTCOST DECIMAL(18,2)
);

DROP TABLE SALES.PRINTMEDIAPLACEMENT;