USE AdventureWorks

ALTER TABLE SALES.MEDIAOUTLET ADD CONSTRAINT IX_MEDIAOUTLET UNIQUE CLUSTERED (
MEDIAOUTLETID
);

-- CLUSTERED INDEX
CREATE CLUSTERED INDEX CIX_PRINTMEDIAPLACEMENT 
ON SALES.PRINTMEDIAPLACEMENT (PRINTMEDIAPLACEMENTID ASC);

--NON CLUSTERED INDEX
CREATE NONCLUSTERED INDEX NCIX_PRINTMEDIAPLACEMENT_NAME 
ON SALES.PRINTMEDIAPLACEMENT (PLACEMENTDATE ASC);

--NON CLUSTERED INDEX
CREATE NONCLUSTERED INDEX NCIX_PRINTMEDIAPLACEMENT
ON [SALES].[PRINTMEDIAPLACEMENT] ([PUBLICATIONDATE],[PALCEMENTCOST])
INCLUDE ([PRINTMEDIAPLACEMENTID],[MEDIAOUTLETID],[PALCEMENTDATE],[RELATEDPRODUCTID])
GO


SELECT PMP.*, MO.CITY 
FROM Sales.PrintMediaPlacement PMP
JOIN Sales.MediaOutlet MO ON PMP.MediaOutletID=MO.MediaOutletID
WHERE PublicationDate BETWEEN '2015-09-1' AND '2015-09-30'
AND PlacementCost BETWEEN 1 AND 2000
ORDER BY PlacementCost DESC;